name: servant-combinators
version: 0.0.2
synopsis: Extra servant combinators for full WAI functionality.
category: web
description: Servant covers most of the data in a raw WAI request, but misses a few fields. This library aims to let handler authors get all the information about a request they need.
author: Adam McCullough <merlinfmct87@gmail.com>
maintainer: Adam McCullough <merlinfmct87@gmail.com>
copyright: © 2023 Adam McCullough
license: MIT
github: TheWizardTower/servant-combinators
tested-with: GHC == 8.8.4
           , GHC == 9.2.4

ghc-options: -Wall -Wwarn -fwarn-tabs

dependencies:
  - aeson
  - base >= 4.14 && < 4.17
  - bytestring
  - clientsession
  - containers
  - cookie
  - http-types
  - servant
  - servant-server
  - tasty
  - text
  - time
  - QuickCheck
  - vault
  - wai

default-extensions:
  - DataKinds
  - FlexibleInstances
  - MultiParamTypeClasses
  - OverloadedStrings
  - ScopedTypeVariables
  - TypeApplications
  - TypeFamilies
  - TypeOperators

library:
  source-dirs:
    - lib
  exposed-modules:
    - Servant.API.Cookies
    - Servant.API.HeaderList
    - Servant.API.QueryString
    - Servant.API.RawQueryString
    - Servant.API.RawRequest

tests:
  check:
    dependencies:
      - async
      - case-insensitive
      - QuickCheck
      - http-client
      - http-conduit
      - servant-combinators
      - tasty
      - tasty-quickcheck
      - warp
    ghc-options: -threaded
    source-dirs:
      - tests
    main: Main.hs
    other-modules:
      - TestCookies
      - TestHeaders
      - TestLib
      - TestQueryString
      - TestRawQueryString
      - TestRawRequest
